//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSCLegendRendererPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSCLegendRendererPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Configuration_Other {
            get {
                object obj = ResourceManager.GetObject("Configuration_Other", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Configuration_X_Spacings {
            get {
                object obj = ResourceManager.GetObject("Configuration_X_Spacings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Configuration_Y_Spacings {
            get {
                object obj = ResourceManager.GetObject("Configuration_Y_Spacings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found {0}..
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a table first..
        /// </summary>
        public static string ErrorMissingTable {
            get {
                return ResourceManager.GetString("ErrorMissingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected table has no valid fields..
        /// </summary>
        public static string ErrorNoFields {
            get {
                return ResourceManager.GetString("ErrorNoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened during a preparation phase..
        /// </summary>
        public static string ErrorValidationFailed {
            get {
                return ResourceManager.GetString("ErrorValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read table data source..
        /// </summary>
        public static string ErrorWrongData {
            get {
                return ResourceManager.GetString("ErrorWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-calculate number of columns (CGM only)..
        /// </summary>
        public static string FormRendererFieldAutoCalculateColumn {
            get {
                return ResourceManager.GetString("FormRendererFieldAutoCalculateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string FormRendererFieldColumn {
            get {
                return ResourceManager.GetString("FormRendererFieldColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEM images in unit boxes..
        /// </summary>
        public static string FormRendererFieldDEM {
            get {
                return ResourceManager.GetString("FormRendererFieldDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FormRendererFieldDescription {
            get {
                return ResourceManager.GetString("FormRendererFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string FormRendererFieldElement {
            get {
                return ResourceManager.GetString("FormRendererFieldElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string FormRendererFieldHeading {
            get {
                return ResourceManager.GetString("FormRendererFieldHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label 1.
        /// </summary>
        public static string FormRendererFieldLabel1 {
            get {
                return ResourceManager.GetString("FormRendererFieldLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label 1 Style.
        /// </summary>
        public static string FormRendererFieldLabel1Style {
            get {
                return ResourceManager.GetString("FormRendererFieldLabel1Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label 2.
        /// </summary>
        public static string FormRendererFieldLabel2 {
            get {
                return ResourceManager.GetString("FormRendererFieldLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label 2 Style.
        /// </summary>
        public static string FormRendererFieldLabel2Style {
            get {
                return ResourceManager.GetString("FormRendererFieldLabel2Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string FormRendererFieldOrder {
            get {
                return ResourceManager.GetString("FormRendererFieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 1.
        /// </summary>
        public static string FormRendererFieldStyle1 {
            get {
                return ResourceManager.GetString("FormRendererFieldStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 2.
        /// </summary>
        public static string FormRendererFieldStyle2 {
            get {
                return ResourceManager.GetString("FormRendererFieldStyle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string FormRendererGroupFields {
            get {
                return ResourceManager.GetString("FormRendererGroupFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Legend Table.
        /// </summary>
        public static string FormRendererSelectLegendTable {
            get {
                return ResourceManager.GetString("FormRendererSelectLegendTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend Renderer.
        /// </summary>
        public static string FormRendererTitle {
            get {
                return ResourceManager.GetString("FormRendererTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GenericButtonBrowse {
            get {
                return ResourceManager.GetString("GenericButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenericButtonCancel {
            get {
                return ResourceManager.GetString("GenericButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GenericButtonRun {
            get {
                return ResourceManager.GetString("GenericButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GenericButtonSave {
            get {
                return ResourceManager.GetString("GenericButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        public static string GenericMessageCompleted {
            get {
                return ResourceManager.GetString("GenericMessageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: see debug file for more information..
        /// </summary>
        public static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenericMessageErrorTitle {
            get {
                return ResourceManager.GetString("GenericMessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer data source does not meet needed requirements..
        /// </summary>
        public static string GenericMessageErrorWrongDatabase {
            get {
                return ResourceManager.GetString("GenericMessageErrorWrongDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string GenericWarningTitle {
            get {
                return ResourceManager.GetString("GenericWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_SymbolStandard {
            get {
                object obj = ResourceManager.GetObject("GSC_SymbolStandard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LegendBoxDEM {
            get {
                object obj = ResourceManager.GetObject("LegendBoxDEM", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
